### ISSUE TITLE
addmoney and spawn_pu commands not working

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#698] opened 2024-04-15 07:19 UTC
**Describe the bug**
the commands addmoney and spawn_pu don't work. they always show up in text chat when you give it a value.

**To Reproduce**
1. Go to any map
2. open console by press the ` key (usually left from number 1 key)
3. type in either command
4. give them a value like 1
5. see that it appears in chat instead

**Expected behavior**
- when you use the addmoney command. it should give you points in addition to what you already had
- when you use spawn_pu command. it should spawn a power up in front of you.

**Affected Platforms**
pc/webgl

**Comment by MotoLegacy** [comment] 2024-09-02 01:43
Duplicate of https://github.com/nzp-team/nzportable/issues/650

**Closed by MotoLegacy** 2024-09-02 01:43 UTC
Labels: bug, FTE, Server
