### ISSUE TITLE
[SERVER] You take fall damage in water.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#304] opened 2023-06-10 20:20 UTC
**Describe the bug**
_A clear and concise description of what the bug is._

In a situation where you would normally take fall damage due to the height you fell, if you fall into a body of water which either is ankle deep or deep enough to the point where you can swim in it and then touch the floor while still being in the water, the water will not cancel your fall damage.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go find/make a map with water.
2. Fall into said water from a height where fall damage is guaranteed.
3. Break your ankles.

**Expected behavior**
_A clear and concise description of what you expected to happen._

You either take fall damage after touching the water surface, or you don't take any fall damage

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/q5jjemxzh10

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

I did **not** test it on

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Unneeded Comment**
_Add any unnecessary comment about the problem here._

It's rare to find a situation like this, but let's future-proof and fix this!

**Comment by BCDeshiG** [comment] 2023-06-10 21:48
I'll be honest, I genuinely couldn't tell you what the intended behaviour is for most water interactions since zombies maps never had it until Zetsubou no Shima in bo3.

Did you say `swim` BTW because that sounds like something left over from quake. I guess Cypress would be able to give you a proper answer on these things.

**Comment by MotoLegacy** [comment] 2023-06-10 23:28
Hey yeah, swimming is not the World at War spec. There is also no scenario in vanilla World at War where the player falls into water. Call of Duty isn't Minecraft either. Someone should investigate (maybe by `noclip`-ing above the water in Shi No Numa?) to see what early Call of Duty does.

As a side note, I have the values for accurate fall damage numbers sitting on my hard drive. So let me know if anyone wants to tackle both determining what the water does and also making fall damage not awful.

As always, thanks for the report.

**Comment by Paindeluxe** [comment] 2023-06-11 00:04
The only issue for me is that stairs in my version of Verrückt are dangerous for the player as you can‘t really walk down them but only fall down them due to the lack of snapping onto the nearest floor upon walking off of one due to that I decided to use water to mitigate this issue just like in minecraft or source engine games that sadly did not help in this case (I also cannot exactly change the stairs due to the fact that I intended to make a verrückt that acts just like the original or that is true to the size from originally Call of Duty: World At War or Call of Duty: Black Ops 1 and 3 Respectively. However fall damage in normal maps works as expected but due to the scale of this map/the stairs of this being strangely sized the fall damage takes affect however in a way which is unpleasant for the player of my map due to as stated before the unorthodox scale of the map. There isn‘t much to do in our case unfortunately.

**Comment by MotoLegacy** [comment] 2023-06-11 00:10
Please keep comments on-topic. If its not about fixing the issue or identifying new information, keep it out of here.

Additionally, use my Verruckt..

**Comment by MotoLegacy** [comment] 2023-06-11 20:49
Why was this closed?

**Comment by Paindeluxe** [comment] 2023-06-11 21:07
I thought that there wasn’t anything that was going to hallen due to this, I decided to close it

**Comment by MotoLegacy** [comment] 2023-06-12 03:39
> I thought that there wasn’t anything that was going to happen due to this, I decided to close it

Unless the issue is addressed or it's confirmed this behavior is on-par with World at War, it is to be treated as a bug and left open. Someone will come along and fix it. Thanks!

**Comment by MotoLegacy** [comment] 2023-06-17 13:19
I've gone ahead and tested this for you as it seems no one else has been able to. Water does not suppress fall damage.

https://github.com/nzp-team/nzportable/assets/26030250/688c1335-6653-4cc1-adcb-67caf420af4b

I will be closing the issue as a result.

However, here are the previously-mentioned fall damage notes I took from World at War in the hopes they can be used by someone else to resolve the issue.
[t4-moto-falldmg.txt](https://github.com/nzp-team/nzportable/files/11779082/t4-moto-falldmg.txt)

**Closed** 2023-06-17 13:20 UTC
Labels: bug
