### ISSUE TITLE
Max zombies decreases after every dog round

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#471] opened 2023-11-21 02:24 UTC
**Describe the bug**

After every dog round, the max zombie count decreases by a random (?) amount, its very noticeable after the 2nd/3rd dog round

**To Reproduce**
1. boot up hangar
2. play through 3 dog rounds (I couldn't find a way to make it happen faster)
3. count the max amount of zombies

i counted zombies by training zombies until they stopped joining for a considerable amount of time, and then counting the difference of my kills before and after i kill the train

**Expected behavior**
max zombies to stay the same

**Screenshots/Footage**

After 2 dog rounds (17 max, tested on 2 different rounds)
![after 2 dog rounds](https://github.com/nzp-team/nzportable/assets/13917665/7a432a36-996b-4361-a59e-9034a295f9f9)
![after 2 dog rounds](https://github.com/nzp-team/nzportable/assets/13917665/0693f82f-ba2d-45ab-a6ec-f5400ab7652e)

After 3 dog rounds (9 max, tested once)
![After 3 dog rounds](https://github.com/nzp-team/nzportable/assets/13917665/bdf9cb31-4009-4149-900d-177d5496143f)
![After 3 dog rounds](https://github.com/nzp-team/nzportable/assets/13917665/dd7a5025-768e-435c-8590-4e594aeeaf51)

While I can't be 100% certain it's dog rounds, It's my biggest lead

**Affected Platforms**

FTE

**Additional context**

I had a stream the other day, in which i encountered this bug, and can be seen being reproduced multiple times

**Comment by MotoLegacy** [comment] 2023-11-21 02:39
duplicate of https://github.com/nzp-team/nzportable/issues/256

**Closed by MotoLegacy** 2023-11-21 02:39 UTC
Labels: bug
