### ISSUE TITLE
[SERVER] Last Stand Invincibility Ends Instantly

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#57] opened 2022-10-18 18:35 UTC
**Describe the bug**
_It's more of an oversight but it wont be fun when it happens._ You can hit and kill yourself by spamming the downed pistols near you.

**To Reproduce**
1. Go to any map (solo)
2. Get downed with quick rerive
3. Spam your pistols on the ground when your about to rerive yourself
4. Die and lose your run
5. (Not needed but applicable) _Cry._

**Expected behavior**
I'm not supposed to die by my Pistols.

**Screenshots/Footage**

https://user-images.githubusercontent.com/104042185/196514129-a91aff8d-0b83-472f-9981-f07fb5e7cedf.mp4

**Side Note**

_I was only opening the console to try and slow my game down since it has to be at like the exact second to when you rerive yourself._

**Comment by MotoLegacy** [comment] 2022-12-27 20:41
Took a look and accidentally discovered this is _intended behavior_, at least as an oversight in Black Ops. Closing as it's not a bug.

**Closed by MotoLegacy** 2022-12-27 20:41 UTC
