### ISSUE TITLE
Grenade self-harm is absurd

### ISSUE THREAD

**Issue by SSleeet** [nzp-team/nzportable#342] opened 2023-08-26 22:58 UTC
**Describe the bug**
Grenades can 1 hit kill the player with jug from ridiculous distances and through walls. A couple of others have said they need to be extremely cautious when handling grenades due to them being able to instantly down you.

**To Reproduce**
1. Stand anywhere relatively close to a grenade

**Expected behavior**
Live

**Affected Platforms**
- PC (and probably other builds)

https://github.com/nzp-team/nzportable/assets/27873551/01475cc4-cc4d-4f26-8296-2b0ad76f0067

**Additional context**
The attached clip doesn't show the grenade hitting me through a wall, but I've had it happen before. In no way should that grenade have killed me with Jug from that distance in one hit.

**Comment by MotoLegacy** [comment] 2023-08-27 00:30
I can't reproduce this, here is me standing directly on top of a grenade with Jugger-Nog. Are you capturing on the latest version? 

https://github.com/nzp-team/nzportable/assets/26030250/80ddb610-1516-4a0d-85a9-80ffc65518d3

**Comment by SSleeet** [comment] 2023-08-27 01:05
I believe I am playing on latest. It appears the damage is inconsistent, and I've only heard from one other person having the issue that it is inconsistent for them as well. Sometimes it kills, sometimes it doesn't even damage.

**Comment by MotoLegacy** [comment] 2023-08-27 02:21
> I believe I am playing on latest. It appears the damage is inconsistent, and I've only heard from one other person having the issue that it is inconsistent for them as well. Sometimes it kills, sometimes it doesn't even damage.
> 
> 

It's based on proximity, its not inconsistent. The closer you are the more damage, so me standing right in front was maximum damage. Some revisions I made earlier today will be deployed in the nightly tonight, so I'd suggest you wait for that to drop and get back to me.

**Comment by MotoLegacy** [comment] 2023-09-12 12:53
Closing because user did not follow up as requested.

**Closed** 2023-09-12 12:53 UTC
Labels: bug
