### ISSUE TITLE
[FTE] Toggle mode on ADS stops right clicking on Mustang and Sallu

### ISSUE THREAD

**Issue by Mr49-SE** [nzp-team/nzportable#847] opened 2024-07-17 14:53 UTC
If you switch to toggle mode on ADS and try to shoot the mustang and sally on the right side , the right click doesnt work . But in Hold mode it works just fine 

**To Reproduce**
1. Get Mustang and Sally on PC
2. Have Toggle mode on ADS
3. Right click to see if the gun shoots 

**Expected behavior**
the gun shouldnt shoot anything at that point . However turning on the hold mode fixes this issue . It should work just fine on the toggle mode just like the hold mode

**Comment by MotoLegacy** [comment] 2024-07-17 14:54
duplicate of https://github.com/nzp-team/nzportable/issues/618

**Closed by MotoLegacy** 2024-07-17 14:54 UTC
Labels: bug
