### ISSUE TITLE
[CO-OP/SERVER] When the lower Player on a Player Tower Crouches the lower and upper Player get Stuck 

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#1025] opened 2024-12-14 18:39 UTC
**Describe the bug**
_A clear and concise description of what the bug is._

When Players Stack on Top of each other and the lower Player Crouches and Uncrouches, the lower Person, and the upper Person standing on Top of the lower Person get stuck. 

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go either "Fegefeuer" or "Firing Range"
2. Get to a Spot where it is possible to jump onto another Persons Head.
3. The lower Person crouches and uncrouches.
4. The lower Person and the upper who is standing on the lower Person of the Player Stack are now locked into each other.

**Expected behavior**
_A clear and concise description of what you expected to happen._

If you try to uncrouch when a Entity is currently occupying the Space necessary to uncrouch then you should not be able to uncrouch. 

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://github.com/user-attachments/assets/864e80ef-8c87-414a-b5ab-a5e229f20879

**Affected Platforms**
_State which platform(s) you've seen the bug occur._
- FTEQW (Windows, Mac, **Linux**, WebGL etc)

_Please also make note of any platforms you DID NOT test on._
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional unwanted Comments**
_Add any unwanted Comments about the problem here._

1. God, that Title is too long.
2. This may also happen with moveable Geometry like `func_train`?

**Comment by MotoLegacy** [comment] 2024-12-29 17:32
Duplicate of https://github.com/nzp-team/nzportable/issues/1026

**Closed by MotoLegacy** 2024-12-29 17:32 UTC
Labels: bug
