### ISSUE TITLE
[Webgl(coop)] after playing coop, quick rev not working

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#420] opened 2023-11-03 15:17 UTC
After playing coop (whether related or not) I played decided to host and I used menu_newmulti and started a server. I bought quick rev, and upon a down with quick rev the game ended instead of reviving me. I tested this again without hosting and the problem occured again twice (both hosting and not)

Quick rev should always revive the player

Only tested on webgl, coop may have interfered

**Comment by MotoLegacy** [comment] 2023-11-03 18:03
I don't understand what you are attempting to describe. Quick Revive should only self-revive on solo. If you are in a co-operative game with multiple players and Quick Revive does not give a self-revive, this works as intended.

Please make sure your report descriptions are detailed, and concise. There's a lot here that is messy and hard to understand.

**Comment by SilentShadows77** [comment] 2023-11-08 06:16
It didnt work while playing solo, after playing some coop matches

**Comment by MotoLegacy** [comment] 2023-11-08 13:51
fixed in https://github.com/nzp-team/quakec/commit/a19658ec9ec79529c1794b7266db2f676d5380b6

**Closed by MotoLegacy** 2023-11-08 13:51 UTC
Labels: bug
