### ISSUE TITLE
[SERVER/3DS]Game curruption

### ISSUE THREAD

**Issue by Trickiy** [nzp-team/nzportable#587] opened 2024-01-07 01:37 UTC
**Describe the bug**
the map textuers will begin to get curupt by first going transparent then lighting will break and most if not all textures will currupt even in the main menu and loading screan and the bottem scre will turn blue.

**To Reproduce**
1. Go to any map
2. go to the main menu
3. enter same/any map
4. back to the main menu 
5.repeat

Expected behavior:
The map reloading consistently no matter how many times it is reloaded.

Affected Platforms:
Tested:
- Nintendo 3DS New
Not Tested:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS Old
- FTEQW (Windows, Mac, Linux, WebGL etc)

Additional context:
Best results on christmass special

**Comment by MotoLegacy** [comment] 2024-11-26 21:50
Tried this ~10 times and could not reproduce, closing

**Closed by MotoLegacy** 2024-11-26 21:50 UTC
Labels: bug
