### ISSUE TITLE
[CLIENT] Random main menu pops up ingame

### ISSUE THREAD

**Issue by oStarist** [nzp-team/nzportable#341] opened 2023-08-26 08:46 UTC
**Describe the bug**
At random times in game, a pure black background "main menu" will appear with a "Join server" button and others, completely ending games regardless of the round you are on.

**To Reproduce**
Honestly it just happens randomly. We haven't found a clear way to properly reproduce this.

**Expected behavior**
To not happen at all I guess? I would only expect this to happen when a button or something is pressed in the actual main menu.

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

https://www.twitch.tv/zombiemanjames/clip/OilyFriendlyMeatloafNononoCat-bQ2b51FCvZi_izwz?filter=clips&range=24hr&sort=time

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

This was only tested on Windows to my knowledge, but probably happens on other systems.

**Additional context**
None.

**Comment by MotoLegacy** [comment] 2023-08-26 12:23
This occurs when the game QuakeC crashes, you can check the console for details of the actual result of the crash, but since this behavior is not a bug I'll have to close the issue. Open a new one with the console logs and it can be fixed!

**Closed by MotoLegacy** 2023-08-26 12:23 UTC
Labels: bug

**Comment by SSleeet** [comment] 2023-08-27 07:05
![image_2023-08-27_014906182](https://github.com/nzp-team/nzportable/assets/27873551/ea44ff9c-4dcd-44a8-8319-859bd575b9b2)

Had the same issue but this time with a screenshot. Happens after box moves but I didn't look into it further than that,

**Comment by oStarist** [comment] 2023-08-27 07:17
Should note that the screenshot taken above is latest.
