### ISSUE TITLE
[VITA] Zombie pathfinding issues, getting stuck on random parts of map

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#459] opened 2023-11-16 15:15 UTC
When playing the Vita version of the game, even after a fresh restart, zombies will constantly get stuck on geometry, running on the spot endlessly until you get close to them. Play on the Vita for a couple of rounds, and by about round 8 you will find yourself having to run around for a couple of minutes at the end of every round mopping up those who got stuck - Below is a collage of examples taken on 4 different maps.

![Vita Bug Compilation](https://github.com/nzp-team/nzportable/assets/139988968/9a6aef90-18cc-46ce-9324-1e00c05d4e47)

**Comment by MotoLegacy** [comment] 2023-11-16 15:16
Duplicate of https://github.com/nzp-team/nzportable/issues/408

**Closed by MotoLegacy** 2023-11-16 15:16 UTC
Labels: bug
