### ISSUE TITLE
[SERVER] Zapper Traps Continue After Timer.

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#180] opened 2023-02-06 22:54 UTC
**Describe the bug**
the zapper trap still kills even after the timer it has runs out. it kills zombies and hurts the player when either try to walk over them.

**To Reproduce**
1. Play on a map that has zapper
2. activate zapper
3. Watch for Electricity to stop
4. walk into the trap
5. die

**Expected behavior**
should not be active after the timer.

**Screenshots/Footage**
![fte-20230206144628-0](https://user-images.githubusercontent.com/34180180/217105547-db993ff3-8dff-4445-ae68-d00d1d6666ef.png)
![fte-20230206144621-0](https://user-images.githubusercontent.com/34180180/217105551-b801f0bb-fe9e-4aae-a072-5da843b95a7e.png)

**Affected Platforms:**
Only Tested on PC...

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- 3DS

**Comment by MotoLegacy** [comment] 2023-02-16 21:32
I'm not able to reproduce this on maps other than your Bunker map, namely, Fegefeuer does not present this issue. Could you reference the .map for that level and see if there is something you may be doing incorrectly?

**Comment by MotoLegacy** [comment] 2023-02-27 15:31
Closing as it was discovered the trap was being set up improperly.

**Closed by MotoLegacy** 2023-02-27 15:31 UTC
