### ISSUE TITLE
[SERVER] The Powerup System causes a crash and gets the Mod unloaded in FTEQW

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#212] opened 2023-02-23 09:26 UTC
**Describe the bug**

The new Powerup cycle that was introduced in https://github.com/nzp-team/quakec/commit/1498f61986f47c0c1b2b470beb32161eaa0443fb is unstable and causes soft crashes.

**To Reproduce**
1. Go to any Map.
2. Play enough to go through all the Powerup Drops?
3. See Crash.

**Expected behavior**

The new system won't crash and just picks your next Powerup drop.

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

![grafik](https://user-images.githubusercontent.com/104042185/220862339-4c9901a0-44aa-4da7-af63-f0baf2c1d032.png)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

- I have seen it occur on FTEQW (PC).

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**

Nope I got nothing for you fella!

**Comment by MotoLegacy** [comment] 2023-02-23 14:31
duplicate of https://github.com/nzp-team/nzportable/issues/209. please make sure issues are unique.

**Closed** 2023-02-23 14:31 UTC
Labels: bug
