### ISSUE TITLE
[VITA] Granade Blackout

### ISSUE THREAD

**Issue by MaeUwU** [nzp-team/nzportable#129] opened 2023-01-18 10:07 UTC
in the vita version, when you throw a granade, sometimes the screen can just went black soon as the granade explode

**Comment by Paindeluxe** [comment] 2023-01-18 11:52
I‘m pretty sure your referring to post #126

**Comment by Paindeluxe** [comment] 2023-01-18 11:53
Not sure though …

**Comment by MotoLegacy** [comment] 2023-01-18 17:29
Yes, this is a duplicate of https://github.com/nzp-team/nzportable/issues/126, which has been resolved.

**Closed** 2023-01-18 17:29 UTC
