### ISSUE TITLE
[CO-OP/SERVER] Multiple tries to revive player

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#81] opened 2022-12-23 23:09 UTC
**Describe the bug**
Sometimes, it can take multiple times to revive a downed player in multiplayer

it's inconsistent, but it'll happen if you try it a few times

**To Reproduce**

1. have a player get downed
2. have the other player revive them (this may take a couple tries)
3. keep holding use, the bar should cycle

**Expected behavior**
I would expect the 

player to be revived after the bar fills up the first time

**Screenshots/Footage**
while in this video there is a zombie attacking, i promise this happened without him there previously
https://user-images.githubusercontent.com/13917665/209412319-08a1347c-9cf8-4eae-9f6b-7f79cdcd75f5.mp4

**Affected Platforms:**
This was only tested on the WebGL build of the game

**Comment by MotoLegacy** [comment] 2023-01-25 03:08
Not able to reproduce this issue by experimenting with heavy packet loss AND forced high pings. Closing.

**Closed by MotoLegacy** 2023-01-25 03:08 UTC
