### ISSUE TITLE
I only have access to the web version, and I cannot use any of these maps. How do I run them?

### ISSUE THREAD

**Issue by MoltenWolf85** [nzp-team/nzportable#966] opened 2024-11-11 14:34 UTC
I only have access to the web version, and I cannot use any of these maps. How do I run them?

How was that off topic? It won't let me use any custom maps.

**Comment by MotoLegacy** [comment] 2024-11-11 16:20
Duplicate of https://github.com/nzp-team/nzportable/issues/946

**Closed by MotoLegacy** 2024-11-11 16:20 UTC
