### ISSUE TITLE
[MAP] Potential waypointing problem in Nacht Der Untoten

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#814] opened 2024-06-26 16:45 UTC
Video:
https://youtu.be/wJtUal_D6Rg

**Comment by MotoLegacy** [comment] 2024-09-02 17:38
I couldn't reproduce this exact issue but could reproduce a very similar one in the same spot, hopefully fixed with https://github.com/nzp-team/assets/commit/42c092be5974419875738f9eb399509446c16a96

**Closed by MotoLegacy** 2024-09-02 17:38 UTC
Labels: bug
