### ISSUE TITLE
HUD damage indicator is inconsistent

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#291] opened 2023-04-25 21:05 UTC
**Describe the bug**
When you take damage, sometimes the blood effect on the HUD is way fainter than it should be.

**To Reproduce**
1. Buy Juggernog (Not sure if this affects things)
2. Let a zombie hit you a few times

**Expected behavior**
At full health, the blood effect should be the same opacity every time.

**Screenshots/Footage**
[https://youtu.be/bEJNRJcD-2o](https://youtu.be/bEJNRJcD-2o)

**Affected Platforms**
Only tested on FTE Linux.

**Additional context**
Seems to be a regression of sorts, need to test without Jug as well as on Windows.

**Comment by BCDeshiG** [comment] 2023-04-25 21:57
After further testing, it seems more consistent than I thought initially.
Without Juggernog everything is as expected.
With Juggernog, the first hit is barely visible. Still need to rule out any weirdness with my Linux set-up though.

**Comment by MotoLegacy** [comment] 2023-04-27 22:12
This was caused by parity changes made to Jugger-Nog and health generation. Jugger-Nog acts by changing the total amount of user health, as opposed to formerly halving damage taken by zombies.

The way the health HUD works is that the opacity of the image is a ratio of (health)/100. This means that it won't show up at all for the first couple of hits.

What should be done is a study of how Call of Duty handles the health display. I think the way it works is that on impact the opacity is based on the actual damage value, and dissipates on a timer based on the initial opacity.

**Comment by MotoLegacy** [comment] 2023-07-18 17:11
fixed in https://github.com/nzp-team/quakec/commit/b691428e3cb380f556108b20f2db6253117cf435

**Closed by MotoLegacy** 2023-07-18 17:11 UTC
Labels: bug, FTE
