### ISSUE TITLE
Multiple Wunderwaffes can be aquired in Co-op

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#411] opened 2023-10-30 05:57 UTC
**Describe the bug**
In Co-op multiple people can get the Wunderwaffe

**To Reproduce**
1. Load up any map with Wunderwaffe in the Mbox (we used fegenfuere)
2. roll the box as both players until each player gets it

**Expected behavior**
Only one person can have the Wunderwaffe at a time

**Screenshots/Footage**

Recorded as it happened 
[Youtube Link](https://youtu.be/oBibWP5UZe4)

**Affected Platforms**

WebGL

**Comment by MotoLegacy** [comment] 2023-10-30 16:53
Cannot reproduce on maps with either mbox version 1 or version 2. Videos attached, closing.


https://github.com/nzp-team/nzportable/assets/26030250/b3377739-2e9a-4e6f-a3a5-1cb227a614f2


https://github.com/nzp-team/nzportable/assets/26030250/621b3630-bcff-4c00-821c-61a634985c1c

**Comment by MotoLegacy** [comment] 2023-10-30 17:27
User clarified out of issue this only happens with the host. Addressed in https://github.com/nzp-team/quakec/commit/060b157a4cfbe651dddcdd7d9d8343b823cdf279

**Closed by MotoLegacy** 2023-10-30 17:27 UTC
Labels: bug, Server
