### ISSUE TITLE
[PSP] freeze/crash/out of memory on load and midgame

### ISSUE THREAD

**Issue by LukoCiphre** [nzp-team/nzportable#328] opened 2023-07-26 14:22 UTC
**Describe the bug**
latest update has prollems ;-;

**To Reproduce**
start x x (load ndu)
load map
gets done loading
freezes
(you cam exit via xmb)
or it resets the psp
(this is weird because it sometimes does and sometimes dosent)
pausing dosent seem to affect anything related to this so
///////
i turned "NoDRM Engine" and "force high memory layout" ON and its playable, 
NDU loaded again, but runs out of memory sometimes (better than the 4screen i guess, the 4screen exists still seperately)
warehouse loaded fine, and runs fine so far 
(encountered trenchgun bug but it causes no lag, written in 2nd post)
i died and it ran out of memory (died with qr and it didnt crash[on a seperate run], so)
![20230726_090000](https://github.com/nzp-team/nzportable/assets/132708551/5e3c6395-960d-448a-8e70-df858f2cfe5b)

https://github.com/nzp-team/nzportable/assets/132708551/c1c13b5a-47c0-4cd2-882e-038804121dae

**Expected behavior**
videogame load game and make shooty pow 
i love nzp
nzp nzp nzp
and the psp is a strange device but i love it too

**Affected Platforms**
psp 3001(64mb)
(ill look at 32mb later)

**Additional context**
i use promod cfw with infinity
idk what yall have but id like to know

**Comment by twylightproto** [comment] 2023-07-27 15:00
It's just about the same for 32mb, I have a 1001 and I usually get it after dying now. It used to just die outta nowhere (this is after I installed the newer release for 32mb. I just don't  like re-opening the came each time

**Comment by LukoCiphre** [comment] 2023-07-29 16:54
game plays good when it plays, everything works, just runs out of memory

**Comment by MotoLegacy** [comment] 2023-07-30 14:19
Duplicate of #295. Glad to hear it had been alleviated a bit during my PSP day, though.

**Closed** 2023-07-30 14:19 UTC
Labels: bug
