### ISSUE TITLE
[3DS] Zombie spawns not properly reset on new run

### ISSUE THREAD

**Issue by AthleticSeafood** [nzp-team/nzportable#876] opened 2024-08-16 05:53 UTC
If a player unlocks an area of a map, when a new run begins the game will still spawn zombies in the previously unlocked areas, resulting in zombies that are stuck behind barriers or doors. Exiting to the main menu and re-entering the map fixes the bug.

To reproduce:
Method 1:
1. Pick a map and start a round
2. Unlock an area
3. Restart through the pause menu

Method 2:
1. Pick a map and start a new round
2. Unlock an area
3. Die
4. Wait for a new game to begin automatically

Tested on Old 3DS
![IMG_20240814_213056](https://github.com/user-attachments/assets/b1993938-bf74-45fa-a3e3-4556d3e2673c)

**Comment by Peter0x44** [comment] 2024-08-16 10:09
I think this is a dup of #59

**Comment by MotoLegacy** [comment] 2024-09-02 02:03
Duplicate of https://github.com/nzp-team/nzportable/issues/59#issuecomment-1869162237

**Closed by MotoLegacy** 2024-09-02 02:03 UTC
Labels: bug
