### ISSUE TITLE
[SWITCH] Port Has Fallen...i think

### ISSUE THREAD

**Issue by MilkyHolic** [nzp-team/nzportable#297] opened 2023-05-07 05:25 UTC
Welp...sounds what it looks like 
the switch port will no longer boot on newer firmware or atmosphere. Error logs display some sort of memory issue and there is no solution to this issue online..trust me ive tried.

how to replicate
-have a cfw switch 
-extract nzp to /switch
-boot into cfw and open homebrew menu by opening app while holding <r>

-wait to be saddened...

menu will load, but maps will immediately crash game on load, sorry switch fans--get a 3ds they better

**Comment by Naievil** [comment] 2023-05-07 05:29
Hi, which switch software version are you using?

**Comment by MilkyHolic** [comment] 2023-05-07 05:31
I cant see due to system update notification but i believe it is upwards of 15.0 (i dont believe ive gone to 16.0)

**Comment by MotoLegacy** [comment] 2023-05-07 17:28
Duplicate of https://github.com/nzp-team/nzportable/issues/284. Please make sure new issues created aren't already reported.

Additionally, "get a 3DS they better" is a completely irrelevant an opinionated statement that bloats bug reports. Be reasonable please, thanks.

Closing.

**Closed** 2023-05-07 17:28 UTC

**Comment by MilkyHolic** [comment] 2023-05-08 00:25
apologies,wrote the report late and night and considered its seriousness rather minimal. Which you couldve likely judged by the titile
