### ISSUE TITLE
[SUGGESTION] Controller Support

### ISSUE THREAD

**Issue by DeckyGamer12** [nzp-team/nzportable#717] opened 2024-04-30 20:05 UTC
**Describe your suggestion**
a feature I would like to be added to the game and for controller players?
it would be nice to have an option to enable "gamepad" in the settings or having a setting especially for those that are non-keyboard players like me. it's just that I'm bad at it.

it should be the same as the other versions like PSVita? like binding the buttons, changing the sensitivity stuff like that.

thank you!

**Comment by MotoLegacy** [comment] 2024-05-12 16:39
This is a duplicate of #362

**Closed by MotoLegacy** 2024-05-12 16:39 UTC
Labels: enhancement
