### ISSUE TITLE
3ds error message (old 3ds ) 

### ISSUE THREAD

**Issue by Ellis243454** [nzp-team/nzportable#1001] opened 2024-12-02 19:21 UTC
Describe the bug
Once I have updated nzp it keeps getting me a error message on my 3ds and I'm not sure if it's my 3ds or nzp but it says failed to allocate soc_buffer

To Reproduce
1. Update the game 
2. Launch the game 

Expected behavior
There should be a black screen for a few seconds like normal and then the error message shows up on the bottom screen 

Screenshots/Footage
![20241202_131847.jpg](https://github.com/user-attachments/assets/7ed53833-20fe-4ae9-98ea-a1d8690002b7)

Affected Platforms
Old 3ds that I know of 

Additional context 
Every other problem I have with the game like a custom map not being supported will crash my entire DS but this bug doesn't do even that

**Comment by DerpedCrusader** [comment] 2024-12-02 19:23
Duplicate of #995

**Closed** 2024-12-02 19:23 UTC
Labels: bug
