### ISSUE TITLE
 A Spawn on Christmas special broken plus game robs you of perks 

### ISSUE THREAD

**Issue by Ellis243454** [nzp-team/nzportable#551] opened 2023-12-26 03:36 UTC
To Reproduce
1. Open nzp 
2. Go into Christmas special 
3. Open the required doors 
4. Watch a crawler spin and a zombie float 
5. Buy a perk 
6. Quickly walk away from the machine 

Screenshots/Footage
https://github.com/nzp-team/nzportable/assets/132875822/aed39b42-0f53-45be-a455-68f8ac2dc139

Affected Platforms

- Nintendo 3DS (Old) 

Additional context
This started on round six whenever I noticed the round didn't end and I also couldn't test the other devices but it probably doesn't work on PSP as well 

I didn't open the whole map as well so I have no clue if others are broken 

Edit: just now noticed the perk thing as I went down for the 3rd time

**Comment by MotoLegacy** [comment] 2023-12-27 19:32
duplicate of #90

**Closed by MotoLegacy** 2023-12-27 19:32 UTC
Labels: bug
