### ISSUE TITLE
[PC] Angle/Offset issues when using sprites with `scale`

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#40] opened 2022-07-06 19:25 UTC
**Describe the bug**
When you use null.spr to point to a .tga sprite, the sprites origin is in the wrong position, causing it to rotate incorrectly

**To Reproduce**

1. make a map with a place_model of a null.spr that points to a real sprite
2. scale it up, because it also uses the null.spr's size (known issue)
3. load up a map
4. look up
5. SPEEN

**Expected behavior**
the sprite should rotate around the center of the sprite while billboarding twoards the player

**Screenshots/Footage**
https://youtu.be/ZwVLsG4MKRk

**Affected Platforms:**

Only tested on FTEQW

**Additional context**
i need to make a report about the scaling, but i have to leave for work in like, 5 minuets lol

**Comment by MotoLegacy** [comment] 2022-07-07 18:37
Of note that this potential issue is not connected to `models/sprites/null.spr` or external textures in any way. Solely an issue with sprites and `scale`.

**Comment by MotoLegacy** [comment] 2022-07-08 22:13
> Of note that this potential issue is not connected to models/sprites/null.spr or external textures in any way. Solely an issue with sprites and scale.

This turned out to be incorrect. `null.spr` had a size of 1x1 with no true center origin, which was the root cause.

Fixed in https://github.com/nzp-team/assets/commit/3ef4813985ac0553dfcd0e23e48e3122f3d066ee

**Closed by MotoLegacy** 2022-07-08 22:13 UTC
