### ISSUE TITLE
[3DS] The Maps are sorted incorrectly.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#66] opened 2022-11-28 17:21 UTC
**Describe the bug**

**To Reproduce**
1. Go to the custom maps
2. Get annoyed by it not being alphabetically sorted

**Expected behavior**
It's sorted alphabetically.

**Screenshots/Footage**
![PC](https://user-images.githubusercontent.com/104042185/204339878-3ceb5861-8ca8-403f-a510-796e8671ab3a.png)

[3DS](https://github.com/nzp-team/nzportable/files/10106068/2032-11-27_19-12-57.644_top.bmp.zip)

**Affected Platforms:**

The 3DS and 2DS Family.

**Additional context**
**IT'S ANNOYING**

**Comment by BCDeshiG** [comment] 2022-11-28 17:38
Last I checked, this also affects Linux (though I'll need to re-verify that)

**Comment by MotoLegacy** [comment] 2023-01-25 02:44
This isn't really an issue -- filesystems are in charge of the order files are sent and we just display what *they* provide. Feel free to open a new issue marked as a suggestion to manually comb through and organize alphabetically, but as it stands this is not a bug :(

**Closed by MotoLegacy** 2023-01-25 02:44 UTC
