### ISSUE TITLE
Perk Prompt inconsistent between maps

### ISSUE THREAD

**Issue by PSPGOENTHUSIAST** [nzp-team/nzportable#547] opened 2023-12-22 00:48 UTC
**Describe the bug**
Most perk machines will not have a prompt to buy. 

**To Reproduce**
Play any map and most or all perk machines will not have a prompt to buy

**Expected behavior**
A prompt is to supposed to pop up that tells you to turn the power on or to buy when you get near a perk

**Affected Platforms**
# Ps Vita and Nintendo switch 
I did not test on other playforms

**Additional context**
I was playing on a older version and everything worked normally until I updated it

**Comment by MotoLegacy** [comment] 2023-12-22 00:49
Duplicate of https://github.com/nzp-team/nzportable/issues/508 -- worth noting they aren't completely inpurchaseable, you just have to take a step back atm.

**Comment by PSPGOENTHUSIAST** [comment] 2023-12-22 00:59
> Duplicate of #508 -- worth noting they aren't completely inpurchaseable, you just have to take a step back atm.

I tried man nothing works

**Comment by MotoLegacy** [comment] 2023-12-23 17:16
Sorry for the misunderstanding -- it took a few days to realize what you meant, and how it was different than #508. I've implemented a proper fix in https://github.com/nzp-team/quakec/commit/96b08dcaba9533df40ba1c7d1ba37cfdfe0fdbc1

**Closed by MotoLegacy** 2023-12-23 17:16 UTC
Labels: bug

**Comment by PSPGOENTHUSIAST** [comment] 2023-12-27 06:58
I appreciate it. Thank you
