### ISSUE TITLE
[PC/MENU] You can hover over menu options through another Active Window

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#140] opened 2023-01-25 13:38 UTC
**Describe the bug**
_A clear and concise description of what the bug is._

While a diffrent Window is opened by for example another Program you can still hover over Options from the NZP menu while also producing noise.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Bootup NZP.
2. Start your favorite Music app without minimizing NZP.
3. Hover over Songs/Menu Options.
4. Hear Clicking.

**Expected behavior**
The mouse cannot interact with the NZP window while the NZP window is either covered up or Inactive.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://user-images.githubusercontent.com/104042185/214577253-89ff9d4d-1913-443b-a60c-a68ca73931f7.mp4

**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.

- FTEQW (Windows, _Mac?_, Linux, etc)

**Additional context**

**DARN YOU** navigate.wav!!!!

**Comment by MotoLegacy** [comment] 2023-02-16 21:40
Not able to reproduce this issue with FTE on Linux. Maybe a Windows issue? Closing for now.


https://user-images.githubusercontent.com/26030250/219493160-5908d55b-c96b-465b-8e26-6496cac9cd20.mp4

**Closed by MotoLegacy** 2023-02-16 21:40 UTC
