### ISSUE TITLE
[PSP] constant crashes on psp fat

### ISSUE THREAD

**Issue by pato4mmc** [nzp-team/nzportable#271] opened 2023-03-24 00:10 UTC
**Describe the bug**
constant crashes, after loading screens, when buying weapon off a wall, just at random
freezes console and then shuts off

**To Reproduce**
play the game for 5 mins

**Expected behavior**
not crash

**Affected Platforms**
psp fat (psp 1k)

**Additional context**
ive tried 32 mb and 64 mb both dont work
however the old version (nazi zombies portable reboot) works like a charm but its lil outdated

**Comment by MotoLegacy** [comment] 2023-03-27 17:22
fixed in https://github.com/nzp-team/dquakeplus/commit/5a16a272c51d7596ac09b6819d22118a28fdc9d1

context:
this was caused by the old SDL2 contained in the old SDK docker container used having quite a lot of issues with instability with less memory available, so it would crash when filling audio buffers sometimes. updating to the new SDK, and the new SDL, has alleviated this issue.

**Closed by MotoLegacy** 2023-03-27 17:22 UTC
Labels: bug
