### ISSUE TITLE
[SERVER]Trigger_Song

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#289] opened 2023-04-23 19:53 UTC
**Describe the bug**
as of right now. Trigger_Song doesn't work. the model never appears in game, and there's no interaction sound. instead you have to use Game_Songplay. Game_songplay is only usable if you have explosive barrels or trigger_once/multiple set up. Trigger_Song lets you activate music of you interact with a certain amount of objects like how in BO1 Kino you interact with rocks.

**To Reproduce**
1. make a test map if you're a mapper.
2. set song in WorldSpawn's entity field 
![image](https://user-images.githubusercontent.com/34180180/233861931-b3bc05a1-a4df-4aad-9a42-377ae96e2032.png)

3. place a Trigger_song
4. compile then play.
5. then see issue

**Expected behavior**
should work as intended. 

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/34180180/233862059-13804684-7767-41d1-8b77-198a26aeb665.png)
![fte-20230423125137-0](https://user-images.githubusercontent.com/34180180/233862104-0375b290-05e7-4fc4-a085-73401901cc6f.png)

**Affected Platforms**
only seen on pc. but i'm assuming it happens on others

**Comment by MotoLegacy** [comment] 2023-04-27 22:16
`trigger_sound` unfortunately had to be removed, outright and intentionally. It was problematic by design — it just allocated a big .WAV and was always limited to FTE because of this, it was ultimately a stupid mistake for me to push it in the first place. I am sorry.

Someone would need to implement a trigger that increments a value on interact in order to restore its functionality as a "classic use interaction". Linked up the same way the barrels in NDU are, where they increment `game_counter` and when it reaches a value it triggers `game_songplay` (or whatever I had called it).

Closing, not an issue.

**Closed** 2023-04-27 22:16 UTC
Labels: bug
