### ISSUE TITLE
[NX] crash when starting any map

### ISSUE THREAD

**Issue by Anviic** [nzp-team/nzportable#284] opened 2023-04-05 17:55 UTC
**Describe the bug*

the game crashes when starting any map, it only allows you to start the map from the console

**To Reproduce**
1. Go to nzp
2. Click on solo
3. Select any map

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/110195327/230163446-2e9ba590-cb17-4974-abbb-fa7aea2215f2.jpg)

**Affected Platforms**
- Nintendo Switch

**Comment by suLac4ever** [comment] 2023-04-07 15:12
Same here on the latest version.
I also tried adding the id1 directory with the original quake files, because as far as I've seen the nzp, which includes the game data sits inside another nzp folder which is like the quake root, which in turn would include other mods and the retail folders like regular quake ... but it changed nothing. The game is still crashing when trying to launch any map.

**Comment by MotoLegacy** [comment] 2023-04-07 15:20
Hi, it seems there is an issue with loading screen data right now, which is the cause of this crash. I have not had much time to work on this recently, but I will try to make time for it.

You can access any map via the console still. `map ndu` for Nacht der Untoten.

Sorry about the trouble.

**Comment by MotoLegacy** [comment] 2023-07-17 14:06
Fixed in https://github.com/nzp-team/quakespasm/pull/39

**Closed** 2023-07-17 14:07 UTC
Labels: bug
