### ISSUE TITLE
Controller compatibility

### ISSUE THREAD

**Issue by Exponentlink** [nzp-team/nzportable#853] opened 2024-07-24 19:59 UTC
I play on an xbox controller and play with the appropriate settings, however the controls seem to be broken. A, B, and LB all do the same thing, which is jump. To aim down with your gun which is LT, it will either throw a grenade, or aim down the sight. X is supposed to be the appropriate button to buy things but it doesnt seem to do anything. Another issue is that there is no way of buying anything. I have to go to my keyboard and press e every time I want to buy anything. I love the maps and the game play a lot, just wanted to bring this to yalls attention!

**Comment by DerpedCrusader** [comment] 2024-07-24 20:01
Duplicate of #362

**Closed** 2024-07-24 20:01 UTC
Labels: bug
