### ISSUE TITLE
[SERVER] You get stuck with a lower hitbox after Dolphin Diving a lot

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#60] opened 2022-11-12 11:55 UTC
**Describe the bug**
You sink into the ground after multiple Dolphin Dives

**To Reproduce**
1. Download my Map where I tested about fall damage [Falldmgtest.zip](https://github.com/nzp-team/nzportable/files/9994868/Falldmgtest.zip)
2. Put it into maps
3. Check how far up you are at the Single 64x64 Crate
4. Dolphin Dive up the crates
5. Fall down and see that your standing lower than normal

**Expected behavior**
You keep the normal standing hitbox after a Dolphin Dive

**Screenshots/Footage**
https://youtu.be/ULbhG1t0jfs
**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.
I only tested on Pc

**Additional context**
This most likely happens due to Dolphin Diving again before you complete standing up?

**Comment by Paindeluxe** [comment] 2022-11-12 11:57
I have no idea why the video is so laggy I hate the mp4 format I also needed to upload it to youtube due to it being over 10mb

**Comment by BCDeshiG** [comment] 2022-11-12 12:19
Oh yeah this bug has existed for a while. You're correct that it's caused by dolphin diving before you've fully stood back up since the height is most likely not reset properly as a result.
That being said, only the camera seems to be affected from what I remember since going prone doesn't affect your hitbox currently.

**Comment by MotoLegacy** [comment] 2022-12-22 15:21
fixed in https://github.com/nzp-team/quakec/commit/950c072fa1d050bf4ca17104a12708bc59ec2846

**Closed by MotoLegacy** 2022-12-22 15:21 UTC
